Feature/235371 add activity channel
es-wolters-kluwer/a3innuva.Importia.SDK pull request #19
Opened 2022-05-27 09:33 UTC by ivan-suarez-wk

Change Epigrah type in Estimation to string

2022-05-27 11:05 UTC, rubencc commented
**NOTA: Para versionar y publicar tienes que modificar los csproj, añadir el tag de version desde la creacion de release y luego lanzar el workflow**

2022-05-27 11:06 UTC, rubencc commented
La rama no ha partido del ultimo commit de la principal

2022-05-27 11:06 UTC, rubencc requested changes

2022-05-27 11:06 UTC, rubencc commented on Importia.SDK/Implementations/a3innuva.Importia.SDK.Serialization/a3innuvaSerializationBinder.cs
> +            typeof(a3innuva.TAA.Migration.SDK.Interfaces.IActivity[]),
Diria que faltan los tipos internos de la actividad

2022-05-27 11:06 UTC, rubencc commented on Importia.SDK/Interfaces/a3innuva.Importia.SDK.Interfaces/Entities/Journal/IJournal.cs
> +        string InvoiceId { get; set; }
Esto no seria un InvoiceCorrelationId

2022-05-27 11:11 UTC, ivan-suarez-wk commented
> **NOTA: Para versionar y publicar tienes que modificar los csproj, añadir el tag de version desde la creacion de release y luego lanzar el workflow**

Vale. No sabía si lo tenía que hacer en la PullRequest

2022-05-27 11:12 UTC, ivan-suarez-wk commented
> 

Hice un merge de principal a la rama que ya estaba creada.

2022-05-27 11:18 UTC, ivan-suarez-wk commented on Importia.SDK/Interfaces/a3innuva.Importia.SDK.Interfaces/Entities/Journal/IJournal.cs
> +        string InvoiceId { get; set; }
No lo quise llamar InvoiceCorrelationId porque cuando exportamos el asiento, en esta proviedad no estará el valor del CorrelationId de la factura, sino el identificador que tendrá la factura en el fichero exportado y que se generamos cada vez que se lanza el proceso de exportación.

2022-05-30 07:01 UTC, ivan-suarez-wk reviewed
Añado un test del binder, que por reflection obtiene las implementaciones de IMigrationEntity y comprueba que estén "bindeadas".

2022-05-30 20:36 UTC, closed without merging